import type { ProjectState } from "./types";

export const initialState: ProjectState = {
  project: {
    name: "冒险者协会告示板 MVP",
    eventName: "CiGA Game Jam 试运行",
    phase: "开发中",
    engine: "Unity",
    engineVersion: "6000.0 LTS",
    targetPlatform: "Windows / WebGL",
    repository: "https://github.com/example/guild-board-jam",
    dependencies: ["Unity Input System", "URP", "Aseprite", "FMOD 可选"],
    rulesVersion: "jam-rules-v0.1",
    collaborationMarkdown:
      "# 协作规则\n\n- 任务必须绑定负责人、验收人和证据。\n- 主策可以参与评分，但不能单独确认自己的结算。\n- 结算阶段先冻结贡献比例；是否获得奖金、奖金金额与付款动作在后续奖金决议中处理。\n- AI 难度评估仅作为参考证据，不直接决定收益。\n",
  },
  members: [
    {
      id: "m1",
      name: "林遥",
      role: "主策",
      primaryDiscipline: "设计",
      conflictReviewer: false,
      joinedAt: "2026-07-03 18:00",
    },
    {
      id: "m2",
      name: "周珩",
      role: "技术负责人",
      primaryDiscipline: "程序",
      conflictReviewer: true,
      joinedAt: "2026-07-03 18:00",
    },
    {
      id: "m3",
      name: "沈澈",
      role: "美术负责人",
      primaryDiscipline: "美术",
      conflictReviewer: true,
      joinedAt: "2026-07-03 18:00",
    },
    {
      id: "m4",
      name: "许舟",
      role: "成员",
      primaryDiscipline: "程序",
      conflictReviewer: false,
      joinedAt: "2026-07-03 18:20",
    },
    {
      id: "m5",
      name: "唐一",
      role: "成员",
      primaryDiscipline: "美术",
      conflictReviewer: false,
      joinedAt: "2026-07-03 18:20",
    },
    {
      id: "m6",
      name: "何雾",
      role: "成员",
      primaryDiscipline: "音频",
      conflictReviewer: false,
      joinedAt: "2026-07-03 18:20",
    },
    {
      id: "m7",
      name: "顾青",
      role: "成员",
      primaryDiscipline: "QA",
      conflictReviewer: false,
      joinedAt: "2026-07-03 18:30",
    },
    {
      id: "m8",
      name: "白屿",
      role: "复核人",
      primaryDiscipline: "制片",
      conflictReviewer: true,
      joinedAt: "2026-07-03 18:30",
    },
    {
      id: "m9",
      name: "赵烁",
      role: "成员",
      primaryDiscipline: "媒体",
      conflictReviewer: false,
      joinedAt: "2026-07-03 19:00",
    },
    {
      id: "m10",
      name: "苏棠",
      role: "收款代表",
      primaryDiscipline: "文档",
      conflictReviewer: true,
      joinedAt: "2026-07-03 19:00",
    },
  ],
  tasks: [
    {
      id: "t1",
      title: "核心循环原型",
      discipline: "设计",
      module: "玩法核心",
      status: "已通过",
      ownerId: "m1",
      collaboratorIds: ["m2"],
      reviewerId: "m8",
      difficultyPlanner: 5,
      difficultyAi: 4,
      difficultyMember: 5,
      completion: 100,
      quality: 1.08,
      timeliness: 1,
      evidenceStrength: 0.95,
      dueAt: "2026-07-04 02:00",
      acceptedAt: "2026-07-04 01:40",
      description: "定义 48 小时内可完成的玩家行动、反馈、胜负条件与第一版关卡节奏。",
      evidence: [
        {
          id: "e1",
          type: "文档",
          label: "核心循环 GDD",
          url: "docs/core-loop.md",
        },
      ],
    },
    {
      id: "t2",
      title: "角色移动与交互控制器",
      discipline: "程序",
      module: "Gameplay",
      status: "提交验收",
      ownerId: "m2",
      collaboratorIds: ["m4"],
      reviewerId: "m1",
      difficultyPlanner: 4,
      difficultyAi: 4,
      difficultyMember: 4,
      completion: 90,
      quality: 1,
      timeliness: 0.95,
      evidenceStrength: 0.9,
      dueAt: "2026-07-04 08:00",
      description: "实现移动、交互检测、失败重置与基础调试 UI。",
      evidence: [
        {
          id: "e2",
          type: "PR",
          label: "PR #12",
          url: "https://github.com/example/guild-board-jam/pull/12",
        },
      ],
    },
    {
      id: "t3",
      title: "主角与场景首版资产",
      discipline: "美术",
      module: "视觉基准",
      status: "进行中",
      ownerId: "m3",
      collaboratorIds: ["m5"],
      reviewerId: "m1",
      difficultyPlanner: 4,
      difficultyAi: 3,
      difficultyMember: 4,
      completion: 75,
      quality: 1,
      timeliness: 1,
      evidenceStrength: 0.8,
      dueAt: "2026-07-04 12:00",
      description: "输出可进入引擎的主角 sprite、场景 tileset 与色彩规范。",
      evidence: [
        {
          id: "e3",
          type: "截图",
          label: "视觉基准截图",
          url: "assets/visual-target.png",
        },
      ],
    },
    {
      id: "t4",
      title: "音效占位与混音规则",
      discipline: "音频",
      module: "反馈",
      status: "已领取",
      ownerId: "m6",
      collaboratorIds: [],
      reviewerId: "m1",
      difficultyPlanner: 2,
      difficultyAi: 2,
      difficultyMember: 2,
      completion: 20,
      quality: 1,
      timeliness: 1,
      evidenceStrength: 0.5,
      dueAt: "2026-07-04 18:00",
      description: "为移动、交互、失败、成功提供可替换音效占位与音量层级。",
      evidence: [],
    },
    {
      id: "t5",
      title: "构建检查与提交包",
      discipline: "制片",
      module: "发布",
      status: "开放领取",
      ownerId: "m10",
      collaboratorIds: ["m7"],
      reviewerId: "m8",
      difficultyPlanner: 3,
      difficultyAi: 3,
      difficultyMember: 3,
      completion: 0,
      quality: 1,
      timeliness: 1,
      evidenceStrength: 0.3,
      dueAt: "2026-07-05 12:00",
      description: "维护最终打包清单、提交说明、运行截图与备份包。",
      evidence: [],
    },
  ],
  reviews: [
    {
      id: "r1",
      raterId: "m2",
      targetId: "m1",
      reliability: 4,
      collaboration: 4,
      craft: 5,
      quality: 4,
      support: 5,
      note: "方向明确，夜间决策及时。",
    },
    {
      id: "r2",
      raterId: "m1",
      targetId: "m2",
      reliability: 5,
      collaboration: 4,
      craft: 5,
      quality: 4,
      support: 4,
      note: "核心实现推进稳定。",
    },
    {
      id: "r3",
      raterId: "m3",
      targetId: "m5",
      reliability: 4,
      collaboration: 4,
      craft: 4,
      quality: 4,
      support: 3,
      note: "资产跟进及时。",
    },
  ],
  appeals: [
    {
      id: "a1",
      memberId: "m3",
      taskId: "t3",
      reason: "美术资产范围增加了两套动画，希望复核难度从 4 调整到 5。",
      status: "待复核",
      createdAt: "2026-07-05 18:30",
    },
  ],
  snapshots: [],
  prizeDecisions: [],
  auditLog: [
    {
      id: "log1",
      actor: "系统",
      action: "创建项目规则版本",
      target: "jam-rules-v0.1",
      createdAt: "2026-07-03 18:00",
    },
    {
      id: "log2",
      actor: "林遥",
      action: "发布任务",
      target: "核心循环原型",
      createdAt: "2026-07-03 18:30",
    },
  ],
};

